[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

[sqlalchemy]
sqlalchemy.url = driver://user:pass@localhost/dbname

[alembic]
script_location = alembic
sqlalchemy.url = postgresql://dietician_qa_user:password123@localhost:5432/dietician_qa
file_template = %%(rev)s_%%(slug)s
date_format = %Y-%m-%d %H:%M:%S
version_path_separator = :
version_locations = %(here)s/alembic/versions
